import { build } from "esbuild";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { parse, stringify } from "yaml";

// Keep the existing schema as the migration source and rollback configuration.
const source = parse(await readFile(".pages.yml", "utf8"));
const media = Object.fromEntries(source.media.map((item) => [item.name, item]));

function convert(field) {
  const result = {
    name: field.name,
    label: field.label,
    widget: field.list ? "list" : field.type === "date" ? "datetime" : field.type,
    required: field.required ?? (field.type === "object" && !field.list),
  };
  if (field.default !== undefined) result.default = field.default;
  if (field.description) result.hint = field.description;
  if (field.pattern) result.pattern = [field.pattern.regex, field.pattern.message];
  if (field.options?.maxlength) result.maxlength = field.options.maxlength;
  if (field.fields) result.fields = field.fields.map(convert);
  if (field.type === "object") result.collapsed = true;
  if (field.list) {
    result.min = field.list.min ?? 0;
    result.collapsed = field.list.collapsible?.collapsed ?? true;
    if (field.list.collapsible?.summary) {
      result.summary = field.list.collapsible.summary.replace(/\{([^}]+)\}/g, "{{$1}}");
    }
  }
  if (field.type === "select") {
    result.options = field.options.values.map(({ name, label }) => ({ value: name, label }));
  }
  if (field.type === "date") {
    result.type = "date";
    result.format = "YYYY-MM-DD";
    result.date_format = "DD.MM.YYYY";
    result.time_format = false;
  }
  if (field.options?.media) {
    const folder = media[field.options.media];
    result.media_folder = `/${folder.input}`;
    // Entry-relative public URLs also work under the GitHub Pages project subpath.
    result.public_folder = `./${folder.output}`;
    result.accept = folder.extensions.map((extension) => `.${extension}`).join(",");
    result.choose_url = false;
  }
  return result;
}

const config = {
  backend: {
    name: "github",
    repo: "landat/step-static-website",
    branch: "main",
    auth_methods: ["token"],
  },
  app_title: "МЕТЕОР — управление сайтом",
  site_url: "https://landat.github.io/step-static-website/",
  media_folder: "assets/photos",
  public_folder: "/step-static-website/assets/photos",
  media_libraries: {
    default: { config: { slugify_filename: true, max_file_size: 50 * 1024 * 1024 } },
    stock_assets: false,
  },
  asset_collections: source.media.map((folder) => ({
    name: folder.name,
    label: folder.label,
    media_folder: `/${folder.input}`,
    public_folder: `./${folder.output}`,
  })),
  output: { omit_empty_optional_fields: false, json: { indent_size: 2 } },
  // One editor owns the entire JSON document: saving a section cannot replace its siblings.
  collections: [{
    name: "website",
    label: "Содержимое сайта",
    editor: { preview: false },
    files: [{
      name: "site",
      label: "Объявление, расписание и другие разделы",
      file: "content/site.json",
      format: "json",
      fields: source.content.flatMap((section) => section.fields.map((field) => ({
        ...convert(field), label: section.label,
      }))),
    }],
  }],
};

await mkdir("admin", { recursive: true });
await writeFile("admin/config.yml", "# Generated by npm run build:cms from .pages.yml. Do not edit by hand.\n" + stringify(config));
// The npm entry bundles translations and optional dependencies locally, unlike the CDN build.
await build({
  entryPoints: ["admin/src/main.js"],
  outdir: "admin/vendor",
  entryNames: "cms",
  chunkNames: "chunks/[name]-[hash]",
  assetNames: "assets/[name]-[hash]",
  bundle: true,
  splitting: true,
  format: "esm",
  minify: true,
  target: ["es2022"],
  loader: { ".png": "file" },
  legalComments: "linked",
  logLevel: "warning",
});
await copyFile("node_modules/@sveltia/cms/LICENSE.txt", "admin/vendor/SVELTIA-LICENSE.txt");
console.log("CMS built: local application, translations and configuration in admin/.");
